services:
    filetend:
        container_name: filetend
        # image: ghcr.io/maca134/filetend:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./src:/srv
        restart: unless-stopped
        command: bun start
        environment:
            - NODE_ENV=production
networks:
    default:
        name: filetend

