/**
 * Extracts file-icon data from the vendored `seti-ui` git dependency
 * (github:jesseweed/seti-ui) into a plain TS data module the frontend can
 * import directly. seti-ui ships icons as raw SVGs plus a `mapping.less`
 * file associating extensions/filenames with an icon name and a Less
 * color variable — there's no JS/JSON API to consume at runtime, so this
 * is a one-time (re-runnable) codegen step rather than a runtime dependency.
 *
 * Run with: bun run scripts/generate-seti-icons.ts
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SETI_UI_DIR = resolve(import.meta.dir, "../node_modules/seti-ui");
const OUTPUT_FILE = resolve(
	import.meta.dir,
	"../src/frontend/lib/seti-icons.generated.ts"
);

// From node_modules/seti-ui/styles/{ui-variables,default-theme}.less.
// seti-ui's palette is small and effectively frozen, so this is hand-copied
// rather than Less-parsed.
const COLOR_PALETTE: Record<string, string> = {
	red: "#cc3e44",
	blue: "#519aba",
	green: "#8dc149",
	yellow: "#cbcb41",
	orange: "#e37933",
	pink: "#f55385",
	purple: "#a074c4",
	grey: "#4d5a5e",
	"grey-light": "#6d8086",
	white: "#d4d7d6",
	ignore: "#41535b",
	"seti-primary": "#519aba", // @seti-primary: @blue
};

type RuleKind = "extension" | "filename" | "partial";

interface Rule {
	kind: RuleKind;
	pattern: string;
	icon: string;
}

function parseMappingRules(mappingLess: string): {
	rules: Rule[];
	iconColors: Map<string, string>;
} {
	const rules: Rule[] = [];
	const iconColors = new Map<string, string>();

	const callRegex =
		/\.icon-(set|partial)\(\s*(["'])((?:(?!\2).)*)\2\s*,\s*(["'])((?:(?!\4).)*)\4\s*,\s*@([\w-]+)\s*\)\s*;/g;

	for (const match of mappingLess.matchAll(callRegex)) {
		const [, mixin, , pattern, , icon, colorVar] = match;
		if (!mixin || !pattern || !icon || !colorVar) continue;

		const kind: RuleKind =
			mixin === "partial" ? "partial" : pattern.startsWith(".") ? "extension" : "filename";

		rules.push({ kind, pattern, icon });

		// First rule to reference an icon wins its color; only used as a
		// fallback for the handful of icons shipped without a baked-in fill.
		if (!iconColors.has(icon)) {
			iconColors.set(icon, colorVar);
		}
	}

	return { rules, iconColors };
}

function readIconSvg(
	iconName: string,
	fallbackColorVar: string | undefined
): { viewBox: string; markup: string } {
	const svgPath = resolve(SETI_UI_DIR, "icons", `${iconName}.svg`);
	const raw = readFileSync(svgPath, "utf-8");

	const svgMatch = raw.match(/<svg([^>]*)>([\s\S]*)<\/svg>/);
	if (!svgMatch) {
		throw new Error(`Could not parse SVG structure for icon "${iconName}"`);
	}
	const [, svgAttrs, inner] = svgMatch;

	// Most icons declare a viewBox directly; a few (e.g. bicep) only declare
	// width/height, so fall back to deriving an equivalent viewBox from those.
	const viewBoxMatch = svgAttrs!.match(/viewBox="([^"]+)"/);
	let viewBox = viewBoxMatch?.[1];
	if (!viewBox) {
		const width = svgAttrs!.match(/\bwidth="([^"]+)"/)?.[1] ?? "32";
		const height = svgAttrs!.match(/\bheight="([^"]+)"/)?.[1] ?? "32";
		viewBox = `0 0 ${width} ${height}`;
	}

	const fallbackHex = COLOR_PALETTE[fallbackColorVar ?? "white"] ?? COLOR_PALETTE.white;

	// Most seti-ui icons bake their own brand color into each <path fill="#...">.
	// A few generic ones (default, lock, clock, todo, info, makefile...) ship
	// with no fill at all and rely on external CSS in the real theme — for
	// those we bake in the color from their first mapping.less rule instead.
	const markup = inner!.replace(/<path(?![^>]*\bfill=)([^>]*)>/g, (_all, attrs: string) => {
		return `<path fill="${fallbackHex}"${attrs}>`;
	});

	return { viewBox, markup };
}

function main() {
	const mappingLess = readFileSync(
		resolve(SETI_UI_DIR, "styles/components/icons/mapping.less"),
		"utf-8"
	);
	const { rules, iconColors } = parseMappingRules(mappingLess);

	const availableIcons = new Set(
		readdirSync(resolve(SETI_UI_DIR, "icons"))
			.filter((f) => f.endsWith(".svg"))
			.map((f) => f.slice(0, -4))
	);

	const iconNames = new Set(rules.map((r) => r.icon));
	iconNames.add("default");
	iconNames.add("folder");

	const missing = [...iconNames].filter((name) => !availableIcons.has(name));
	if (missing.length > 0) {
		throw new Error(`Icon names referenced by mapping.less but missing an SVG asset: ${missing.join(", ")}`);
	}

	const icons: Record<string, { viewBox: string; markup: string }> = {};
	for (const name of iconNames) {
		icons[name] = readIconSvg(name, iconColors.get(name));
	}

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/generate-seti-icons.ts — do not edit by hand.");
	lines.push("// Source: github:jesseweed/seti-ui (MIT licensed). Re-run the script to update.");
	lines.push("");
	lines.push('export type SetiRuleKind = "extension" | "filename" | "partial";');
	lines.push("");
	lines.push("export interface SetiRule {");
	lines.push("\tkind: SetiRuleKind;");
	lines.push("\tpattern: string;");
	lines.push("\ticon: string;");
	lines.push("}");
	lines.push("");
	lines.push("export interface SetiIconData {");
	lines.push("\tviewBox: string;");
	lines.push("\tmarkup: string;");
	lines.push("}");
	lines.push("");
	lines.push('export const SETI_DEFAULT_ICON = "default";');
	lines.push('export const SETI_FOLDER_ICON = "folder";');
	lines.push("");
	lines.push(`export const SETI_ICONS: Record<string, SetiIconData> = ${JSON.stringify(icons, null, "\t")};`);
	lines.push("");
	lines.push(`export const SETI_RULES: SetiRule[] = ${JSON.stringify(rules, null, "\t")};`);
	lines.push("");

	writeFileSync(OUTPUT_FILE, lines.join("\n"));
	console.log(
		`Wrote ${iconNames.size} icons and ${rules.length} rules to ${OUTPUT_FILE}`
	);
}

main();
